# -*- coding: utf-8 -*-
"""Crazy Vinyl Shop — static site generator.

Reads data/*.json and writes every route as real HTML, plus the compact
listing index the storefront fetches.

    python tools/build.py

Routes produced:
    /  /proizvodi/  /ploce/  /diskovi/  /majice/  /solje/  /ostalo/
    /rasprodaja/  /proizvod/<slug>/  /korpa/  /checkout/  /kontakt/
    /politika-privatnosti/  /404.html
"""

import argparse
import hashlib
import json
import os
import re
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from template import (  # noqa: E402
    e, page, vinyl, marquee, eyebrow, crumbs, set_logos, set_asset_version,
    SITE_URL,
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data')

# Fields the storefront needs for cards, filters, search and the cart.
# Tracklist and notes stay out — those are rendered into the product pages.
INDEX_FIELDS = [
    'id', 'slug', 'artist', 'title', 'category', 'price', 'salePrice', 'currency',
    'available', 'onSale', 'condition', 'format', 'genre', 'year', 'country',
    'origin', 'addedAt', 'trackCount', 'hasNotes',
]


# Every generated file is written with LF. Without this, Git on Windows
# (core.autocrlf=true) rewrites them to CRLF on checkout, warns on each file and
# makes the whole site look changed after every build.
GITATTRIBUTES = """# Generated by tools/build.py — keep it. It stops Git from
# rewriting line endings on every build.

* text=auto eol=lf

*.png   binary
*.jpg   binary
*.jpeg  binary
*.webp  binary
*.gif   binary
*.ico   binary
*.woff  binary
*.woff2 binary
*.pdf   binary
"""


def asset_fingerprint():
    """Short hash of every stylesheet and script, for cache-busting."""
    h = hashlib.sha1()
    for folder in ('css', 'js'):
        d = os.path.join(ROOT, 'assets', folder)
        for name in sorted(os.listdir(d)):
            if name.endswith(('.css', '.js')):
                with open(os.path.join(d, name), 'rb') as fh:
                    h.update(name.encode())
                    h.update(fh.read())
    return h.hexdigest()[:8]


def read(name):
    with open(os.path.join(DATA, name), encoding='utf-8') as fh:
        return json.load(fh)


LINK_RE = re.compile(r'((?:href|src)=")/([^"]*)"')


def path_prefix(rel_out, base):
    """How this page should reach the site root.

    Pages are generated with root-absolute links (/assets/..., /proizvod/...)
    and rewritten here. Without --base that becomes a relative hop, so the site
    works at a domain root, inside a GitHub Pages project sub-path, or straight
    off the file system. With --base it becomes an absolute path under that
    prefix, which is what a project site needs for 404.html to resolve from any
    depth.
    """
    if base:
        return base.rstrip('/') + '/'
    depth = rel_out.replace(os.sep, '/').count('/')
    return './' if depth == 0 else '../' * depth


def localize(html, rel_out, base):
    prefix = path_prefix(rel_out, base)
    return LINK_RE.sub(lambda m: m.group(1) + prefix + m.group(2) + '"', html)


def write(rel, content):
    path = os.path.join(ROOT, rel.replace('/', os.sep))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(content)


def price_txt(value):
    if value is None or value == '':
        return 'Cena na upit'
    return f'{value:,}'.replace(',', '.') + ' RSD'


def eff_price(p):
    if p.get('onSale') and p.get('salePrice'):
        return p['salePrice']
    return p.get('price')


def tax_line(p):
    return ' · '.join(str(x) for x in (p.get('format'), p.get('genre'), p.get('year')) if x)


def display_name(p):
    return ' – '.join(x for x in (p.get('artist'), p.get('title')) if x) or p['slug']


# ---------------------------------------------------------------------------
# shared blocks
# ---------------------------------------------------------------------------

def artwork(p, tag='OMOT / ARTWORK'):
    """The placeholder names the file it is waiting for."""
    return f'''<figure class="sleeve" data-art="{e(p['slug'])}">
        <div class="ph">
          <span class="ph__tag">{e(tag)}</span>
          <span class="ph__mid">
            {f'<span class="ph__artist">{e(p["artist"])}</span>' if p.get('artist') else ''}
            {f'<span class="ph__title">{e(p["title"])}</span>' if p.get('title') else ''}
          </span>
          <span class="ph__code">{e(p['slug'])}.jpg</span>
        </div>
      </figure>'''


def cat_rail(categories, current):
    def link(href, label, slug):
        cur = ' aria-current="page"' if current == slug else ''
        return f'<a class="cat-rail__link" href="{e(href)}"{cur}>{e(label)}</a>'

    links = [link('/proizvodi/', 'Sve', 'all')]
    links += [link(c['href'], c['label'], c['slug']) for c in categories]
    links.append(link('/rasprodaja/', 'Rasprodaja', 'rasprodaja'))
    return f'<nav class="cat-rail" aria-label="Kategorije">{"".join(links)}</nav>'


FILTERS_HOST = '<div data-filters-host></div>'

FILTER_SHEET = f'''<aside class="sheet" id="filterSheet" role="dialog" aria-modal="true" aria-label="Filteri" tabindex="-1">
  <div class="sheet__head">
    <h2 class="drawer__title">Filteri</h2>
    <button type="button" class="search__close" data-close-filters aria-label="Zatvori filtere">Zatvori</button>
  </div>
  <div class="sheet__body">
    <div class="filters">{FILTERS_HOST}</div>
  </div>
  <div class="sheet__foot">
    <button type="button" class="btn btn--ghost" data-clear-all>Obriši</button>
    <button type="button" class="btn" data-apply-filters>Prikaži</button>
  </div>
</aside>'''


def shop_head(*, title, lede, breadcrumb=None, head_class='', title_class='page-head__title'):
    bc = crumbs(breadcrumb) if breadcrumb else ''
    lede_html = f'<p class="page-head__lede">{lede}</p>' if lede else ''
    return f'''<section class="page-head {head_class}">
  <div class="page-head__disc" aria-hidden="true">{vinyl(label='CVS', speed=0.7)}</div>
  <div class="wrap page-head__inner">
    {bc}
    <h1 class="{title_class}">{title}</h1>
    {lede_html}
  </div>
</section>'''


def shop_main(*, categories, current, empty_hint=''):
    """The catalogue machinery: filters, toolbar, grid, paging, mobile sheet."""
    fixed = current if current not in ('all', 'rasprodaja') else ''
    return f'''{cat_rail(categories, current)}
<section class="section section--tight">
  <div class="wrap">
    <div class="shop" id="shop" data-fixed-category="{e(fixed)}" data-sale-only="{'true' if current == 'rasprodaja' else 'false'}">
      <aside class="filters" aria-label="Filteri">{FILTERS_HOST}</aside>
      <div>
        <form class="toolbar" role="search">
          <label class="sr-only" for="shopSearch">Pretraga u ovoj selekciji</label>
          <input class="range__input" id="shopSearch" type="search" placeholder="Pretraži izvođača ili naslov" style="max-width:20rem">
          <p class="toolbar__count" id="resultCount" role="status" aria-live="polite"></p>
          <div class="toolbar__right">
            <button type="button" class="btn btn--ghost filter-toggle" data-open-filters aria-expanded="false" aria-controls="filterSheet">Filteri</button>
            <span class="select">
              <label class="sr-only" for="sortSelect">Sortiranje</label>
              <select id="sortSelect"></select>
            </span>
          </div>
        </form>
        <div class="chips" id="activeFilters" style="padding-block:.9rem" hidden></div>
        <div class="grid-products" id="grid">
          <noscript><p class="text-dim">Katalog sa filterima zahteva JavaScript. Svi naslovi su dostupni i preko <a href="/sitemap.xml">mape sajta</a>.</p></noscript>
        </div>
        <div class="loadmore" id="loadMore"></div>
        {empty_hint}
      </div>
    </div>
  </div>
</section>
{FILTER_SHEET}'''


def shop_body(**kw):
    empty_hint = kw.pop('empty_hint', '')
    categories = kw.pop('categories')
    current = kw.pop('current')
    return shop_head(**kw) + shop_main(categories=categories, current=current, empty_hint=empty_hint)


# ---------------------------------------------------------------------------
# home
# ---------------------------------------------------------------------------

def home_body(site, categories, counts, products, wordmark=None):
    # The drawn lockup says the same thing as the type stack, so the alt text
    # carries it and the heading stays a real heading either way.
    if wordmark:
        hero_wordmark = (
            '<h1 class="hero-word hero-word--img">'
            f'<img src="{e(wordmark)}" alt="Crazy Vinyl Shop"></h1>')
    else:
        hero_wordmark = ('<h1 class="hero-word">'
                         '<span class="hero-word__line"><span>Crazy</span></span>'
                         '<span class="hero-word__line"><span>Vinyl</span></span>'
                         '<span class="hero-word__line"><span>Shop</span></span></h1>')
    store = site['store']
    tattoo = site['tattoo']
    total = len(products)
    avail = sum(1 for p in products if p['available'])

    crate_rows = []
    for i, c in enumerate(categories):
        n = counts.get(c['slug'], 0)
        crate_rows.append(f'''<a class="crate__row" href="{e(c['href'])}">
        <span class="crate__n">{i + 1:03d}</span>
        <span>
          <span class="crate__label">{e(c['label'])}</span>
          <span class="crate__blurb">{e(c['blurb'])}</span>
        </span>
        <span class="crate__side">
          <span class="crate__count">{n}</span>
          <span class="crate__meta">{e(c['code'])} · {e(c['rpm'])}</span>
        </span>
      </a>''')

    hours_rows = ''.join(
        f'<div class="hours__row{" is-closed" if h["time"].lower().startswith("zatvoreno") else ""}">'
        f'<span>{e(h["day"])}</span><span>{e(h["time"])}</span></div>'
        for h in store['hours']
    )

    return f'''<section class="hero-rig" id="heroRig">
  <div class="hero-stage">
    <canvas class="tv" id="tvStatic" aria-hidden="true"></canvas>
    <div class="tv-lines" aria-hidden="true"></div>
    <div class="tv-roll" aria-hidden="true"></div>
    <div class="hero-inner">
      <p class="hero-rail">
        <span>{e(store['street'])}</span>
        <span>{e(store['city'])} · {e(site['brand']['country'])}</span>
        <span id="heroTally"><b>{total}</b> naslova &nbsp;/&nbsp; <b>{avail}</b> na stanju</span>
      </p>

      <div class="hero-type">
        {hero_wordmark}
        <p class="hero-lede">{e(site['brand']['tagline'])}. Radnja u Kragujevcu i onlajn katalog.</p>
      </div>

      <div class="hero-actions">
        <a class="btn" href="/proizvodi/">Istraži kolekciju</a>
        <a class="btn btn--ghost" href="/rasprodaja/">Rasprodaja</a>
        <span class="hero-scroll"><span class="hero-scroll__line" aria-hidden="true"></span> Skroluj u ploču</span>
      </div>
    </div>

    <div class="hero-disc" id="heroDisc">
      {vinyl(label='CVS', speed=1)}
    </div>

  </div>
</section>

<section class="section paper grooved section--under-hero" id="ponuda">
  <div class="wrap">
    {eyebrow('Odeljenja / Sections', paper=True)}
    <h2 class="t-display t-display--lg" style="padding-block:.6rem 1.5rem">Prođi kroz gajbe</h2>
    <div class="crate">{''.join(crate_rows)}</div>
  </div>
</section>

<section class="section">
  <div class="wrap">
    <div style="display:flex;flex-wrap:wrap;gap:1rem;align-items:flex-end;justify-content:space-between">
      <div>
        {eyebrow('Novo u ponudi')}
        <h2 class="t-display t-display--lg" style="padding-top:.5rem">Sveže na polici</h2>
      </div>
      <a class="link-cat" href="/proizvodi/?sort=newest">Ceo katalog</a>
    </div>
    <div class="grid-products" id="newIn" style="padding-top:2rem"></div>
  </div>
</section>

<div id="genreMarquee">{marquee(['ROCK', 'JAZZ', 'METAL', 'PUNK', 'ELECTRONIC', 'HIP HOP', 'POP', 'BLUES', 'EX-YU'])}</div>

<section class="section">
  <div class="wrap">
    {eyebrow('Izbor radnje / Selected')}
    <h2 class="t-display t-display--lg" style="padding-block:.5rem 2rem">Sa gramofona</h2>
    <div class="selected" id="selected"></div>
  </div>
</section>

<section class="section paper board">
  <div class="wrap">
    <div style="display:flex;flex-wrap:wrap;gap:1rem;align-items:flex-end;justify-content:space-between">
      <div>
        {eyebrow('Rasprodaja', paper=True)}
        <h2 class="t-display t-display--lg" style="padding-top:.5rem">Sniženo <span id="saleCount">0</span></h2>
      </div>
      <a class="link-cat" href="/rasprodaja/">Stranica rasprodaje</a>
    </div>
    <div class="grid-products" id="saleBand" style="padding-top:2rem"></div>
  </div>
</section>

<section class="section paper" id="radnja">
  <div class="wrap">
    {eyebrow('Radnja / Kragujevac', paper=True)}
    <h2 class="t-display t-display--lg" style="padding-block:.5rem 2rem">Dođi i prelistaj</h2>
    <div class="band">
      <div>
        <p class="t-body">Crazy Vinyl Shop je fizička radnja u Kragujevcu. Ploče, diskovi i ostalo stoje na policama — može se pregledati, slušati i pitati. Onlajn katalog je ista roba, samo popisana.</p>
        <div class="hours" style="margin-top:1.5rem">{hours_rows}</div>
      </div>
      <div class="panel">
        <span class="panel__corner">Adresa</span>
        <div class="contact-list">
          <div class="contact-list__row">
            <span class="contact-list__k">Adresa</span>
            <span class="contact-list__v">{e(store['street'])}<br>{e(store['city'])}, {e(site['brand']['country'])}</span>
          </div>
          <div class="contact-list__row">
            <span class="contact-list__k">Telefon</span>
            <span class="contact-list__v"><a href="tel:{e(store['phoneHref'])}">{e(store['phone'])}</a></span>
          </div>
          <div class="contact-list__row" style="border-bottom:0;padding-bottom:0">
            <span class="contact-list__k">E-mail</span>
            <span class="contact-list__v"><a href="mailto:{e(store['email'])}">{e(store['email'])}</a></span>
          </div>
        </div>
        <a class="btn btn--ghost" href="/kontakt/">Kontakt &amp; Tattoo</a>
      </div>
    </div>
  </div>
</section>

<section class="section" id="tattoo">
  <div class="wrap">
    <div class="band">
      <div>
        {eyebrow('Tattoo studio')}
        <h2 class="t-display t-display--lg" style="padding-block:.5rem 1rem">{e(tattoo['name'])}</h2>
        <p class="t-body text-dim">{e(tattoo['note'])}</p>
      </div>
      <div class="panel panel--ink">
        <span class="panel__corner">Sicario</span>
        <div class="contact-list">
          <div class="contact-list__row">
            <span class="contact-list__k">Telefon</span>
            <span class="contact-list__v"><a href="tel:{e(tattoo['phoneHref'])}">{e(tattoo['phone'])}</a></span>
          </div>
          <div class="contact-list__row" style="border-bottom:0;padding-bottom:0">
            <span class="contact-list__k">E-mail</span>
            <span class="contact-list__v"><a href="mailto:{e(tattoo['email'])}">{e(tattoo['email'])}</a></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>'''


# ---------------------------------------------------------------------------
# product detail
# ---------------------------------------------------------------------------

POS_RE = re.compile(r'^([A-Fa-f])(\d{1,2})?\s*[–\-\.]?\s*(.*)$')
DUR_RE = re.compile(r'\s(\d{1,2}:\d{2})\s*$')


def split_tracks(tracks):
    """Group into sides when the source positions make that possible.

    Returns [(side_label, [(position, name, duration), ...]), ...].
    Track names are preserved exactly as the source shows them.
    """
    sides = []
    current = None
    plain = []

    for raw in tracks:
        m = POS_RE.match(raw)
        side = m.group(1).upper() if m and m.group(2) else None
        if side:
            pos = f'{side}{m.group(2)}'
            name = m.group(3).strip()
            if not name:
                name = raw
            if current is None or current[0] != side:
                current = (side, [])
                sides.append(current)
            d = DUR_RE.search(name)
            dur = d.group(1) if d else ''
            if dur:
                name = DUR_RE.sub('', name).strip()
            current[1].append((pos, name, dur))
        else:
            plain.append(raw)

    if sides and not plain:
        return sides
    if sides and plain:
        # keep the stray lines (announcements, venue notes) in their own block
        return sides + [('', [('', t, '') for t in plain])]
    return [('', [('', t, '') for t in plain])] if plain else []


def tracks_markup(tracks):
    groups = split_tracks(tracks)
    if not groups:
        return ''
    only = len(groups) == 1
    out = []
    for side, rows in groups:
        if side:
            label = f'Strana {side}'
        elif only:
            label = 'Numere'
        else:
            # lines the source carries alongside the sides (venue, broadcast notes)
            label = 'Uz izdanje'
        head = f'<p class="tracks__sidehead">{label}</p>'
        body = ''.join(
            f'''<div class="tracks__row">
              <span class="tracks__pos">{e(pos) if pos else '·'}</span>
              <span class="tracks__name">{e(name)}{f'<span class="dur">{e(dur)}</span>' if dur else ''}</span>
            </div>''' for pos, name, dur in rows
        )
        out.append(f'<div class="tracks__side">{head}{body}</div>')
    return f'<div class="tracks">{"".join(out)}</div>'


def product_body(p, site):
    sold = not p['available']
    sale = bool(p.get('onSale') and p.get('salePrice'))
    price = eff_price(p)

    specs = [
        ('Format', p.get('format')),
        ('Žanr', p.get('genre')),
        ('Godina', p.get('year')),
        ('Zemlja', p.get('country')),
        ('Stanje', p.get('condition')),
        ('Poreklo', p.get('origin')),
        ('Kategorija', {'ploce': 'Ploče', 'diskovi': 'Diskovi', 'majice': 'Majice',
                        'solje': 'Šolje', 'ostalo': 'Ostalo'}.get(p['category'], p['category'])),
        ('Kat. broj', f"CVS-{p['id']}"),
    ]
    spec_rows = ''.join(
        f'<div class="specs__row"><span class="specs__k">{e(k)}</span><span class="specs__v">{e(v)}</span></div>'
        for k, v in specs if v not in (None, '', 0)
    )

    notes_html = ''
    if p.get('notes'):
        paras = ''.join(f'<p>{e(para)}</p>' for para in p['notes'].split('\n\n') if para.strip())
        notes_html = f'''<section style="padding-top:2rem">
        {eyebrow('Beleške')}
        <div class="notes" style="padding-top:.9rem">{paras}</div>
      </section>'''

    tl = tracks_markup(p.get('tracklist') or [])
    tracks_html = f'''<section style="padding-top:2rem">
      {eyebrow('Numere')}
      <div style="padding-top:.9rem">{tl}</div>
    </section>''' if tl else ''

    buy = (
        f'''<span class="pdp__status pdp__status--out">Rasprodato</span>
        <p class="text-dim" style="flex-basis:100%;font-size:var(--step--1)">Ovaj naslov je trenutno rasprodat i ne može se dodati u korpu.
        Javite nam se ako želite obaveštenje kada ponovo stigne.</p>'''
        if sold else
        f'''<span class="qty">
          <button type="button" class="qty__btn" data-qty-dec aria-label="Smanji količinu">−</button>
          <span class="qty__val" id="pdpQty" aria-live="polite">1</span>
          <button type="button" class="qty__btn" data-qty-inc aria-label="Povećaj količinu">+</button>
        </span>
        <button type="button" class="btn" id="pdpAdd" data-slug="{e(p['slug'])}">Dodaj u korpu</button>
        <span class="pdp__status pdp__status--in">Na stanju</span>'''
    )

    return f'''<section class="page-head">
  <div class="wrap">
    {crumbs([('Početna', '/'), ('Proizvodi', '/proizvodi/'),
             ({'ploce': 'Ploče', 'diskovi': 'Diskovi', 'majice': 'Majice', 'solje': 'Šolje', 'ostalo': 'Ostalo'}.get(p['category'], 'Ostalo'), f"/{p['category']}/"),
             (display_name(p), None)])}
  </div>
</section>

<section class="section section--tight">
  <div class="wrap">
    <div class="pdp" id="pdp" data-slug="{e(p['slug'])}">
      <div class="pdp__art">
        <div class="pdp__stage" tabindex="0" role="group" aria-label="Omot i ploča — pomeri da izvučeš ploču">
          <div class="pdp__disc">{vinyl(label=(p.get('artist') or p.get('title') or 'CVS')[:3].upper(), speed=1)}</div>
          <div class="pdp__sleeve">{artwork(p, tag='OMOT / ARTWORK')}</div>
        </div>
        <div class="pdp__deck">
          <button type="button" class="pdp__rpm" data-rpm="1" aria-pressed="true">33⅓ RPM</button>
          <button type="button" class="pdp__rpm" data-rpm="1.36" aria-pressed="false">45 RPM</button>
          <span class="t-meta text-dim">Samo vizuelno — ne pušta zvuk</span>
        </div>
      </div>

      <div>
        {eyebrow(f"Kat. CVS-{p['id']}")}
        {f'<h1 class="pdp__artist">{e(p["artist"])}</h1>' if p.get('artist') else ''}
        <p class="pdp__title">{e(p.get('title') or p['slug'])}</p>
        {'' if p.get('artist') else '<h1 class="sr-only">' + e(display_name(p)) + '</h1>'}

        <div class="pdp__buy">
          <span class="pdp__price">
            {f'<s>{e(price_txt(p["price"]))}</s>' if sale else ''}
            {e(price_txt(price))}
          </span>
          {buy}
        </div>

        {eyebrow('Informacije')}
        <div class="specs" style="margin-top:.9rem">{spec_rows}</div>

        {tracks_html}
        {notes_html}
      </div>
    </div>
  </div>
</section>

<section class="section related">
  <div class="wrap">
    {eyebrow('Iz iste gajbe')}
    <h2 class="t-display" style="padding-block:.5rem 1.5rem">Slično po žanru</h2>
    <div class="grid-products" id="related"></div>
  </div>
</section>'''


# ---------------------------------------------------------------------------
# cart / checkout / contact / privacy / 404
# ---------------------------------------------------------------------------

def cart_body():
    return f'''<section class="page-head">
  <div class="wrap page-head__inner">
    {crumbs([('Početna', '/'), ('Korpa', None)])}
    <h1 class="page-head__title">Korpa</h1>
    <p class="page-head__lede">Pregled izabranih naslova. Količine i sadržaj korpe se pamte i posle osvežavanja stranice.</p>
  </div>
</section>
<section class="section section--tight paper">
  <div class="wrap">
    <div class="cart-page">
      <div class="cart-table" id="cartTable"></div>
      <aside class="summary" id="cartSummary" aria-label="Pregled korpe"></aside>
    </div>
  </div>
</section>'''


def checkout_body(site):
    pm = site['checkout']['paymentMethod']
    return f'''<section class="page-head">
  <div class="wrap page-head__inner">
    {crumbs([('Početna', '/'), ('Korpa', '/korpa/'), ('Kasa', None)])}
    <h1 class="page-head__title">Kasa</h1>
    <p class="page-head__lede">Popunite podatke za dostavu. Narudžbenicu potvrđujemo e-mailom ili telefonom.</p>
  </div>
</section>

<section class="section section--tight paper">
  <div class="wrap">
    <div id="checkoutEmpty" hidden>
      <div class="empty">
        <div class="empty__disc">{vinyl(label='CVS', spin=False)}</div>
        <p class="t-display">Korpa je prazna</p>
        <p class="text-dim" style="max-width:44ch">Dodajte naslov iz kataloga pa se vratite na kasu.</p>
        <a class="btn" href="/proizvodi/">Pogledaj katalog</a>
      </div>
    </div>

    <div class="receipt" id="checkoutReceipt" hidden></div>

    <div class="checkout" id="checkoutLayout">
      <form id="checkoutForm" novalidate>
        <fieldset class="fieldset">
          <legend class="fieldset__legend">Način isporuke</legend>
          <label class="radio-card">
            <input type="radio" name="payment" value="{e(pm['value'])}" checked>
            <span>
              <strong>{e(pm['label'])}</strong>
              <span class="text-dim" style="display:block;font-size:.9em;padding-top:.3rem">{e(pm['note'])}</span>
            </span>
          </label>
        </fieldset>

        <fieldset class="fieldset" style="padding-top:2rem">
          <legend class="fieldset__legend">Podaci za dostavu</legend>
          <div class="form-grid form-grid--2">
            <div class="field field--full">
              <label class="field__label" for="name">Ime i prezime / naziv firme <span class="req">*</span></label>
              <input class="input" id="name" name="name" type="text" autocomplete="name" required>
              <span class="field__error" aria-live="polite"></span>
            </div>
            <div class="field">
              <label class="field__label" for="email">E-mail <span class="req">*</span></label>
              <input class="input" id="email" name="email" type="email" autocomplete="email" required>
              <span class="field__error" aria-live="polite"></span>
            </div>
            <div class="field">
              <label class="field__label" for="phone">Kontakt telefon <span class="req">*</span></label>
              <input class="input" id="phone" name="phone" type="tel" autocomplete="tel" required>
              <span class="field__error" aria-live="polite"></span>
            </div>
            <div class="field field--select">
              <label class="field__label" for="country">Država <span class="req">*</span></label>
              <select id="country" name="country" required></select>
              <span class="field__error" aria-live="polite"></span>
            </div>
            <div class="field">
              <label class="field__label" for="city">Grad <span class="req">*</span></label>
              <input class="input" id="city" name="city" type="text" autocomplete="address-level2" required>
              <span class="field__error" aria-live="polite"></span>
            </div>
            <div class="field field--full">
              <label class="field__label" for="address">Adresa za dostavu <span class="req">*</span></label>
              <input class="input" id="address" name="address" type="text" autocomplete="street-address" required>
              <span class="field__error" aria-live="polite"></span>
            </div>
            <div class="field field--full">
              <label class="field__label" for="note">Napomena</label>
              <textarea class="textarea" id="note" name="note" rows="3"></textarea>
              <span class="field__error" aria-live="polite"></span>
            </div>
          </div>
        </fieldset>

        <div style="padding-top:1.5rem;display:grid;gap:1rem">
          <p class="notice">Online plaćanje karticom nije aktivno. Narudžbenica se šalje radnji, a plaćanje i isporuka idu preko Post Express-a.</p>
          <button type="submit" class="btn btn--block" id="checkoutSubmit">Potvrdi narudžbenicu</button>
          <a class="link-cat" href="/korpa/">Vrati se u korpu</a>
        </div>
      </form>

      <aside class="summary" id="orderSummary" aria-label="Narudžbenica"></aside>
    </div>
  </div>
</section>'''


def contact_body(site):
    store = site['store']
    tattoo = site['tattoo']
    hours_rows = ''.join(
        f'<div class="hours__row{" is-closed" if h["time"].lower().startswith("zatvoreno") else ""}">'
        f'<span>{e(h["day"])}</span><span>{e(h["time"])}</span></div>'
        for h in store['hours']
    )
    return f'''<section class="page-head">
  <div class="page-head__disc" aria-hidden="true">{vinyl(label='KG', speed=0.6)}</div>
  <div class="wrap page-head__inner">
    {crumbs([('Početna', '/'), ('Kontakt & Tattoo', None)])}
    <h1 class="page-head__title">Kontakt<br>&amp; Tattoo</h1>
    <p class="page-head__lede">Radnja i tattoo studio dele istu adresu u Kragujevcu. Pozovite, pišite ili dođite.</p>
  </div>
</section>

{marquee(['CRAZY VINYL SHOP', 'KRAGUJEVAC', 'SICARIO TATTOO', 'CRVENOG BARJAKA 21'], reverse=True, speed='34s')}

<section class="section paper">
  <div class="wrap">
    <div class="backcover">
      <div class="panel">
        <span class="panel__corner">Radnja</span>
        {eyebrow('Crazy Vinyl Shop', paper=True)}
        <div class="contact-list">
          <div class="contact-list__row">
            <span class="contact-list__k">Adresa</span>
            <span class="contact-list__v">{e(store['street'])}<br>{e(store['city'])}, {e(site['brand']['country'])}</span>
          </div>
          <div class="contact-list__row">
            <span class="contact-list__k">Broj</span>
            <span class="contact-list__v"><a href="tel:{e(store['phoneHref'])}">{e(store['phone'])}</a></span>
          </div>
          <div class="contact-list__row">
            <span class="contact-list__k">E-mail</span>
            <span class="contact-list__v"><a href="mailto:{e(store['email'])}">{e(store['email'])}</a></span>
          </div>
          <div class="contact-list__row" style="border-bottom:0;padding-bottom:0">
            <span class="contact-list__k">Radno vreme</span>
            <span class="contact-list__v" style="font-size:1rem;font-weight:400">
              <span class="hours" style="display:grid">{hours_rows}</span>
            </span>
          </div>
        </div>
      </div>

      <div class="panel panel--ink">
        <span class="panel__corner">Tattoo</span>
        {eyebrow(tattoo['name'])}
        <p class="t-body text-dim">{e(tattoo['note'])}</p>
        <div class="contact-list">
          <div class="contact-list__row">
            <span class="contact-list__k">Broj</span>
            <span class="contact-list__v"><a href="tel:{e(tattoo['phoneHref'])}">{e(tattoo['phone'])}</a></span>
          </div>
          <div class="contact-list__row" style="border-bottom:0;padding-bottom:0">
            <span class="contact-list__k">E-mail</span>
            <span class="contact-list__v"><a href="mailto:{e(tattoo['email'])}">{e(tattoo['email'])}</a></span>
          </div>
        </div>
      </div>
    </div>

    <div style="padding-top:clamp(2rem,1rem+3vw,4rem)">
      {eyebrow('Lokacija', paper=True)}
      <div class="map-embed" style="margin-top:.9rem">
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5058.979196834431!2d20.91077437619572!3d44.011167671087414!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47572182fe1f03eb%3A0xcf478c351c2d3859!2sCrazy%20Vinyl%20Shop!5e1!3m2!1sen!2srs!4v1789569888680!5m2!1sen!2srs"
          title="Crazy Vinyl Shop na mapi — {e(store['address'])}"
          loading="lazy"
          allowfullscreen
          referrerpolicy="strict-origin-when-cross-origin"></iframe>
      </div>
      <p class="t-meta" style="padding-top:.8rem">
        <a class="link-cat" href="https://www.google.com/maps/search/?api=1&amp;query={e(store['address'].replace(' ', '+'))}" target="_blank" rel="noopener">Otvori u Google mapama</a>
      </p>
    </div>

    <div style="padding-top:clamp(2rem,1rem+3vw,4rem)">
      {eyebrow('Poručivanje i dostava', paper=True)}
      <h2 class="t-display" style="padding-block:.5rem 1rem">Kako ide isporuka</h2>
      <div class="t-body">
        <p>Narudžbenica se šalje sa stranice Kasa. Isporuka i plaćanje idu preko Post Express-a — pouzećem u Srbiji, export u inostranstvo. Troškovi dostave za Srbiju se obračunavaju po
        <a href="{e(site['checkout']['priceListUrl'])}" target="_blank" rel="noopener">cenovniku Post Express-a</a>, a za inostranstvo po zonama koje se vide na kasi.</p>
        <p>Za pitanja o stanju ploče, rezervaciji ili ličnom preuzimanju u radnji — pozovite ili pišite.</p>
      </div>
    </div>
  </div>
</section>'''


def privacy_body(doc):
    toc = []
    sections = []
    for i, sec in enumerate(doc['sections']):
        heading = sec.get('heading') or ''
        sid = f'sec-{i}'
        if heading:
            toc.append(f'<a class="toc__link" href="#{sid}">{e(heading)}</a>')
        blocks = []
        for b in sec['blocks']:
            if b['type'] == 'p':
                blocks.append(f'<p>{e(b["text"])}</p>')
            else:
                lis = ''.join(f'<li><span>{e(x)}</span></li>' for x in b['items'])
                blocks.append(f'<ul class="doc__list">{lis}</ul>')
        head = f'<h2 class="doc__h" id="{sid}">{e(heading)}</h2>' if heading else ''
        sections.append(f'<section class="doc__section">{head}{"".join(blocks)}</section>')

    return f'''<section class="page-head">
  <div class="wrap page-head__inner">
    {crumbs([('Početna', '/'), ('Politika privatnosti', None)])}
    <h1 class="page-head__title">Politika<br>privatnosti</h1>
  </div>
</section>
<section class="section section--tight paper">
  <div class="wrap">
    <div class="doc-layout">
      <nav class="toc" aria-label="Sadržaj dokumenta">
        <p class="footer__col-title" style="color:var(--terra-dark)">Sadržaj</p>
        {''.join(toc)}
      </nav>
      <div class="doc">{''.join(sections)}</div>
    </div>
  </div>
</section>'''


def notfound_body():
    return f'''<section class="nf">
  <div class="nf__inner">
    <div style="width:clamp(120px,20vw,200px)">{vinyl(label='404', speed=1.2)}</div>
    <p class="nf__code">404</p>
    {eyebrow('Strana nije nađena')}
    <p class="t-body text-dim" style="max-width:44ch">Ova ploča nije u gajbi. Možda je naslov promenio adresu ili je link pogrešan.</p>
    <div style="display:flex;gap:.6rem;flex-wrap:wrap;justify-content:center">
      <a class="btn" href="/proizvodi/">Ceo katalog</a>
      <a class="btn btn--ghost" href="/">Početna</a>
    </div>
  </div>
</section>'''


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def find_logo(stem, fallback=None):
    """The shop's own file for this slot, whatever format it arrived in.

    `fallback` lets one master serve several slots — the shop has a single
    transparent logo it wants everywhere, so the record label falls back to it
    rather than needing its own copy.
    """
    for name in (stem, fallback):
        if not name:
            continue
        for ext in ('svg', 'png', 'webp', 'jpg', 'jpeg'):
            path = os.path.join(ROOT, 'images', name + '.' + ext)
            if os.path.isfile(path):
                return path
    return None


def prepare_logo(stem, target_px, fallback=None):
    """Return the URL to use for a logo slot, resizing the master if needed.

    The file dropped into images/ is usually an export at full resolution — the
    header mark renders at well under 60px, so serving a 1254px master there
    would cost more than every other asset on the page put together. A
    derivative is generated beside it and referenced instead; the master stays
    untouched as the source, and is re-derived whenever it changes.
    """
    src = find_logo(stem, fallback)
    if not src:
        return None, None

    name = os.path.basename(src)
    if src.lower().endswith('.svg'):
        return '/images/' + name, None  # already resolution-independent

    try:
        from PIL import Image
    except ImportError:
        # No Pillow: ship the master rather than no logo, and say so.
        return '/images/' + name, 'master (install Pillow to resize)'

    out_dir = os.path.join(ROOT, 'images', 'gen')
    os.makedirs(out_dir, exist_ok=True)
    out_name = '%s-%d.webp' % (os.path.splitext(os.path.basename(src))[0], target_px)
    out_path = os.path.join(out_dir, out_name)

    if not os.path.isfile(out_path) or os.path.getmtime(out_path) < os.path.getmtime(src):
        im = Image.open(src)
        im = im.convert('RGBA') if im.mode in ('RGBA', 'LA', 'P') else im.convert('RGB')
        if im.width > target_px:
            height = max(1, round(im.height * target_px / im.width))
            im = im.resize((target_px, height), Image.LANCZOS)
        im.save(out_path, 'WEBP', quality=88, method=6)

    saved = '%dkB from %dkB' % (
        round(os.path.getsize(out_path) / 1024), round(os.path.getsize(src) / 1024))
    return '/images/gen/' + out_name, saved


def main():
    ap = argparse.ArgumentParser(description='Build the Crazy Vinyl Shop site.')
    ap.add_argument('--base', default='',
                    help='Sub-path the site is served from, e.g. /crazy-vinyl-shop '
                         'for a GitHub Pages project site. Omit for relative links.')
    args = ap.parse_args()
    base = args.base.strip()
    if base and not base.startswith('/'):
        base = '/' + base

    # header mark renders under 80px; the record label up to ~340px; the hero
    # lockup as wide as the hero column
    set_asset_version(asset_fingerprint())

    logo, logo_note = prepare_logo('logo', 256)
    label_logo, label_note = prepare_logo('logo-label', 640, fallback='logo')
    wordmark, wordmark_note = prepare_logo('natpislogo2', 1000, fallback='natpislogo')
    set_logos(logo, label_logo, wordmark)

    products = read('products.json')
    site = read('site.json')
    categories = read('categories.json')
    privacy = read('privacy.json')

    counts = Counter(p['category'] for p in products)
    genre_counts = Counter(p['genre'] for p in products if p.get('genre'))
    top_genres = [g for g, _ in genre_counts.most_common(6)]

    # ---- compact listing index -------------------------------------------
    rows = []
    for p in products:
        rows.append([
            p['id'], p['slug'], p.get('artist', ''), p.get('title', ''), p['category'],
            p.get('price'), p.get('salePrice') or 0, p.get('currency', 'RSD'),
            bool(p['available']), bool(p.get('onSale')), p.get('condition', ''),
            p.get('format', ''), p.get('genre', ''), p.get('year'), p.get('country', ''),
            p.get('origin', ''), p.get('addedAt', ''),
            len(p.get('tracklist') or []), bool(p.get('notes')),
        ])
    write('data/index.json', json.dumps({'fields': INDEX_FIELDS, 'rows': rows}, ensure_ascii=False))

    # ---- image manifest: only slugs that really have a file ---------------
    img_dir = os.path.join(ROOT, 'images', 'products')
    os.makedirs(img_dir, exist_ok=True)
    have = sorted({
        os.path.splitext(f)[0] for f in os.listdir(img_dir)
        if f.lower().endswith(('.jpg', '.jpeg', '.png', '.webp', '.avif'))
    })
    write('data/images.json', json.dumps(have, ensure_ascii=False))

    shell = dict(site=site, categories=categories, counts=counts, genres=top_genres)
    written = []

    def emit(rel, **kw):
        write(rel, localize(page(**kw, **shell), rel, base))
        written.append(rel)

    # ---- home ------------------------------------------------------------
    emit('index.html',
         title='Crazy Vinyl Shop — ploče, diskovi i muzička roba iz Kragujevca',
         description=site['brand']['description'],
         path='/', page_kind='home', body=home_body(site, categories, counts, products, wordmark),
         jsonld={
             '@context': 'https://schema.org', '@type': 'Store',
             'name': 'Crazy Vinyl Shop', 'url': SITE_URL,
             'telephone': site['store']['phone'], 'email': site['store']['email'],
             'address': {'@type': 'PostalAddress', 'streetAddress': site['store']['street'],
                         'addressLocality': site['store']['city'], 'addressCountry': 'RS'},
             'sameAs': [s['url'] for s in site['social']],
         })

    # ---- catalogue -------------------------------------------------------
    emit('proizvodi/index.html',
         title='Proizvodi — ceo katalog | Crazy Vinyl Shop',
         description=f'Ceo katalog Crazy Vinyl Shop-a: {len(products)} naslova, filtriranje po žanru, formatu, godini i dostupnosti.',
         path='/proizvodi/', page_kind='shop',
         body=shop_body(title='Proizvodi', lede=f'Ceo katalog — {len(products)} naslova. Filtriraj po žanru, formatu, godini, zemlji i dostupnosti.',
                        categories=categories, current='all',
                        breadcrumb=[('Početna', '/'), ('Proizvodi', None)]))

    for c in categories:
        n = counts.get(c['slug'], 0)
        empty_hint = ''
        if n == 0:
            empty_hint = f'''<div class="empty" style="margin-top:2rem">
              <div class="empty__disc">{vinyl(label=c['code'], spin=False)}</div>
              <p class="t-display">{e(c['emptyState'])}</p>
              <p class="text-dim" style="max-width:44ch">Kategorija postoji i čeka robu. U međuvremenu pogledajte ostatak kataloga.</p>
              <a class="btn" href="/ploce/">Pogledaj ploče</a>
            </div>'''
        emit(f'{c["slug"]}/index.html',
             title=f'{c["label"]} | Crazy Vinyl Shop',
             description=f'{c["blurb"]} {n} naslova u ponudi.' if n else f'{c["blurb"]} {c["emptyState"]}',
             path=c['href'], page_kind='shop',
             body=shop_body(title=e(c['label']), lede=e(c['blurb']),
                            categories=categories, current=c['slug'],
                            breadcrumb=[('Početna', '/'), ('Proizvodi', '/proizvodi/'), (c['label'], None)],
                            empty_hint=empty_hint))

    # ---- sale ------------------------------------------------------------
    on_sale = [p for p in products if p.get('onSale') and p.get('salePrice')]
    sale_empty = '' if on_sale else f'''<div class="empty" style="margin-top:2rem">
      <div class="empty__disc">{vinyl(label='SALE', spin=False)}</div>
      <p class="t-display">Trenutno nema aktivne rasprodaje</p>
      <p class="text-dim" style="max-width:46ch">Nijedan naslov nije na sniženju. Kada radnja spusti cene, naslovi se automatski pojavljuju ovde.</p>
      <div style="display:flex;gap:.6rem;flex-wrap:wrap;justify-content:center">
        <a class="btn btn--sale" href="/ploce/">Pogledaj ploče</a>
        <a class="btn btn--ghost" href="/proizvodi/">Ceo katalog</a>
      </div>
    </div>'''

    sale_head = f'''<section class="page-head sale-head">
  <div class="wrap page-head__inner">
    {crumbs([('Početna', '/'), ('Rasprodaja', None)])}
    <h1 class="sale-head__title">Sale<br>Rasprodaja</h1>
    <p class="page-head__lede">Sniženi naslovi iz radnje. Prikazuju se samo cene koje stoje u katalogu.</p>
  </div>
</section>
<div class="sale-strip">{marquee(['SALE', 'RASPRODAJA', 'LIMITED', 'SNIŽENO', 'LAST COPY'], speed='28s')}</div>'''

    emit('rasprodaja/index.html',
         title='Rasprodaja | Crazy Vinyl Shop',
         description='Naslovi na sniženju u Crazy Vinyl Shop-u.',
         path='/rasprodaja/', page_kind='shop', body_class='is-sale',
         body=sale_head + shop_main(categories=categories, current='rasprodaja',
                                    empty_hint=sale_empty))

    # ---- product pages ---------------------------------------------------
    by_slug = {}
    for p in products:
        by_slug.setdefault(p['slug'], p)

    for p in by_slug.values():
        label = display_name(p)
        desc_bits = [x for x in (p.get('format'), p.get('genre'), p.get('year'), p.get('country')) if x]
        desc = f'{label} — {", ".join(str(x) for x in desc_bits)}. {price_txt(eff_price(p))}.'
        if not p['available']:
            desc += ' Rasprodato.'
        offer = {
            '@type': 'Offer',
            'priceCurrency': 'RSD',
            'availability': 'https://schema.org/InStock' if p['available'] else 'https://schema.org/OutOfStock',
            'url': f"{SITE_URL}/proizvod/{p['slug']}/",
        }
        if eff_price(p):
            offer['price'] = eff_price(p)
        emit(f'proizvod/{p["slug"]}/index.html',
             title=f'{label} | Crazy Vinyl Shop',
             description=desc[:300],
             path=f'/proizvod/{p["slug"]}/', page_kind='product', og_type='product',
             body=product_body(p, site),
             jsonld={
                 '@context': 'https://schema.org', '@type': 'Product',
                 'name': label,
                 'sku': f"CVS-{p['id']}",
                 'brand': {'@type': 'Brand', 'name': p.get('artist') or 'Crazy Vinyl Shop'},
                 'category': p['category'],
                 'offers': offer,
             })

    # ---- the rest --------------------------------------------------------
    emit('korpa/index.html', title='Korpa | Crazy Vinyl Shop',
         description='Pregled korpe pre poručivanja.', path='/korpa/',
         page_kind='cart', body=cart_body())

    emit('checkout/index.html', title='Kasa | Crazy Vinyl Shop',
         description='Podaci za dostavu i potvrda narudžbenice. Isporuka preko Post Express-a.',
         path='/checkout/', page_kind='checkout', body=checkout_body(site))

    emit('kontakt/index.html', title='Kontakt & Tattoo | Crazy Vinyl Shop',
         description=f'Crazy Vinyl Shop, {site["store"]["address"]}. Telefon {site["store"]["phone"]}. Sicario Tattoo Studio.',
         path='/kontakt/', page_kind='contact', body=contact_body(site),
         jsonld={
             '@context': 'https://schema.org', '@type': 'Store',
             'name': 'Crazy Vinyl Shop',
             'address': {'@type': 'PostalAddress', 'streetAddress': site['store']['street'],
                         'addressLocality': site['store']['city'], 'addressCountry': 'RS'},
             'telephone': site['store']['phone'], 'email': site['store']['email'],
         })

    emit('politika-privatnosti/index.html', title='Politika privatnosti | Crazy Vinyl Shop',
         description='Politika privatnosti Crazy Vinyl Shop-a.',
         path='/politika-privatnosti/', page_kind='doc', body=privacy_body(privacy))

    emit('404.html', title='Strana nije nađena | Crazy Vinyl Shop',
         description='Ova strana ne postoji.', path='/404.html',
         page_kind='doc', body=notfound_body())

    # ---- sitemap + robots ------------------------------------------------
    urls = ['/', '/proizvodi/', '/rasprodaja/', '/kontakt/', '/politika-privatnosti/',
            '/korpa/', '/checkout/'] + [c['href'] for c in categories]
    urls += [f'/proizvod/{p["slug"]}/' for p in by_slug.values()]
    sm = ['<?xml version="1.0" encoding="UTF-8"?>',
          '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for u in urls:
        sm.append(f'  <url><loc>{SITE_URL}{u}</loc></url>')
    sm.append('</urlset>')
    write('sitemap.xml', '\n'.join(sm) + '\n')
    write('robots.txt', f'User-agent: *\nAllow: /\nSitemap: {SITE_URL}/sitemap.xml\n')
    # GitHub Pages would otherwise run the output through Jekyll
    write('.nojekyll', '')

    # Every generated file is written with LF. Without this, Git on Windows
    # (core.autocrlf=true) rewrites them to CRLF on checkout and warns on every
    # file, and the whole site looks changed on each build.
    write('.gitattributes', GITATTRIBUTES)

    # ---- report ----------------------------------------------------------
    print(f'pages written        : {len(written)}')
    print(f'products             : {len(by_slug)}')
    for c in categories:
        print(f'  {c["label"]:<10}: {counts.get(c["slug"], 0)}')
    print(f'  na stanju  : {sum(1 for p in products if p["available"])}')
    print(f'  rasprodato : {sum(1 for p in products if not p["available"])}')
    print(f'  na sniženju: {len(on_sale)}')
    print(f'images present       : {len(have)} (placeholders for the rest)')
    print(f'index.json rows      : {len(rows)}')
    print(f'asset version        : {asset_fingerprint()}')
    print('links                : ' + ('absolute under ' + base if base else 'relative (portable)'))
    print('header logo          : ' + (logo or 'typographic fallback')
          + (' [' + logo_note + ']' if logo_note else ''))
    print('record label logo    : ' + (label_logo or 'typographic fallback')
          + (' [' + label_note + ']' if label_note else ''))
    print('hero wordmark        : ' + (wordmark or 'typographic fallback')
          + (' [' + wordmark_note + ']' if wordmark_note else ''))


if __name__ == '__main__':
    main()
